### ISSUE TITLE
Twitterをされているメンバーさんのアカウントリスト

### ISSUE THREAD

**Issue by shogo0525** [caster-inc/we_are_hiring#1]
タイトル通りなのですが、Twitterをされているメンバーさんのアカウントリストがあったら嬉しいです！

よろしくお願いいたします。

**Comment by shogo0525** [comment]
`要望は enhancement ラベル` だと思うのですが、ラベルをつける権限がなさそうです..!

**Comment by corocn** [comment]
> Twitterをされているメンバーさんのアカウントリスト

まとめます...!!

> 要望は enhancement ラベル だと思うのですが、ラベルをつける権限がなさそうです..!

おぉお・・これは失念していました。確認しますー

**Comment by shogo0525** [comment]
早速ありがとうございます！
よろしくお願いします 😄

**Comment by corocn** [comment]
@shogo0525 基本エンジニアだけですが、のせていいよ〜って人から随時掲載してってますー
https://github.com/caster-inc/we_are_hiring/blob/master/twitter.md

**Comment by corocn** [comment]
ラベルは、こちら側でつける運用にしますね

**Comment by shogo0525** [comment]
迅速にありがとうございます!! 🐦 

ラベル運用、承知です！
