### ISSUE TITLE
各プロダクトの技術スタックが知りたい

### ISSUE THREAD

**Issue by 13imi** [caster-inc/we_are_hiring#4]
タイトル通り、各プロダクトの技術スタックが知りたいです。
もしどこかにまとまっていたらそのURLでも結構です。
よろしくお願いいたします。

**Comment by corocn** [comment]
よっしゃ！対応します！

**Comment by corocn** [comment]
@13imi @renyamizuno が足してくれましたー

**Comment by 13imi** [comment]
bosyuの技術スタックページ読みました！
ありがとうございます！
